# typed: false
# frozen_string_literal: true

# Homebrew formula for CERT-X-GEN (cxg)
# A polyglot execution engine for vulnerability detection
#
# Generated by .github/workflows/update-formula.yml on each cert-x-gen
# release. Edit the workflow, not this file -- a hand edit here is
# overwritten by the next release.
class Cxg < Formula
  desc "Polyglot execution engine for vulnerability detection"
  homepage "https://github.com/Bugb-Technologies/cert-x-gen"
  version "1.4.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/Bugb-Technologies/cert-x-gen/releases/download/v1.4.0/cxg-darwin-amd64"
      sha256 "bb40d633acdb728f407b04fe3c2cd5655fe08a1059ea9ae79d1f3aa9e9cc04a2"
    end
    on_arm do
      url "https://github.com/Bugb-Technologies/cert-x-gen/releases/download/v1.4.0/cxg-darwin-arm64"
      sha256 "7e722a8ee95c8a9425c0f7e0fc477aa21d6529d76226edad8bb603f16545ffcf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Bugb-Technologies/cert-x-gen/releases/download/v1.4.0/cxg-linux-amd64"
      sha256 "77d5b2c52fb44ccdb939bd1e10a909b388769239199ce09b9ab9414fb0a3e94e"
    end
    on_arm do
      url "https://github.com/Bugb-Technologies/cert-x-gen/releases/download/v1.4.0/cxg-linux-arm64"
      sha256 "f07c028717a6a7f293b68a5ebb8d2cf45ca4f5d74c766022696727aa9c985509"
    end
  end

  def install
    bin.install Dir["cxg-*"].first => "cxg"
  end

  # Templates are fetched at first use, not at install time. Running
  # `cxg template update` from post_install writes outside the formula
  # prefix, which Homebrew's install sandbox denies -- it failed the
  # install rather than the download. Tell the user instead.
  def caveats
    <<~EOS
      To download vulnerability detection templates, run:
        cxg template update

      Templates will be installed to ~/.cert-x-gen/templates/
    EOS
  end

  test do
    assert_match "cxg", shell_output("#{bin}/cxg --version")
  end
end
