# typed: false
# frozen_string_literal: true

# Homebrew formula for CERT-X-GEN (cxg)
# A polyglot execution engine for vulnerability detection
#
# Generated by .github/workflows/update-formula.yml on each cert-x-gen
# release. Edit the workflow, not this file -- a hand edit here is
# overwritten by the next release.
class Cxg < Formula
  desc "Polyglot execution engine for vulnerability detection"
  homepage "https://github.com/Bugb-Technologies/cert-x-gen"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/Bugb-Technologies/cert-x-gen/releases/download/v1.2.0/cxg-darwin-amd64"
      sha256 "8741e7c16b1c95c607d5d794449ca73c8006a862a96bcbc1d36bf4708f523c71"
    end
    on_arm do
      url "https://github.com/Bugb-Technologies/cert-x-gen/releases/download/v1.2.0/cxg-darwin-arm64"
      sha256 "917a57e8e11ec766608306d46471063466a2b89e20b12c4002d745a373bfa17a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Bugb-Technologies/cert-x-gen/releases/download/v1.2.0/cxg-linux-amd64"
      sha256 "5a8a7ca2dc51ecb3399e343a71b549a3284469c0f250f204cfe82474180d4eac"
    end
    on_arm do
      url "https://github.com/Bugb-Technologies/cert-x-gen/releases/download/v1.2.0/cxg-linux-arm64"
      sha256 "e6301a32e54e91410f4a96c87cb5d3f586398e2e39be5303c34b0a51a4561f68"
    end
  end

  def install
    bin.install Dir["cxg-*"].first => "cxg"
  end

  # Templates are fetched at first use, not at install time. Running
  # `cxg template update` from post_install writes outside the formula
  # prefix, which Homebrew's install sandbox denies -- it failed the
  # install rather than the download. Tell the user instead.
  def caveats
    <<~EOS
      To download vulnerability detection templates, run:
        cxg template update

      Templates will be installed to ~/.cert-x-gen/templates/
    EOS
  end

  test do
    assert_match "cxg", shell_output("#{bin}/cxg --version")
  end
end
