# typed: false
# frozen_string_literal: true

# Homebrew formula for CERT-X-GEN (cxg)
# A polyglot execution engine for vulnerability detection
#
# Generated by .github/workflows/update-formula.yml on each cert-x-gen
# release. Edit the workflow, not this file -- a hand edit here is
# overwritten by the next release.
class Cxg < Formula
  desc "Polyglot execution engine for vulnerability detection"
  # @comment -- "brew info / brew home open the cxg product site, cxg.bugb.io"
  homepage "https://cxg.bugb.io"
  version "1.5.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/Bugb-Technologies/cert-x-gen/releases/download/v1.5.0/cxg-darwin-amd64"
      sha256 "d7b7073e41982a79fd629b325a37f45b4e0f1d715101604fc8dc3c8c357dc803"
    end
    on_arm do
      url "https://github.com/Bugb-Technologies/cert-x-gen/releases/download/v1.5.0/cxg-darwin-arm64"
      sha256 "09bdacad27e4fb977589ebcfbec25e037636c93448afc3d493b2f3fc0045ae5d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Bugb-Technologies/cert-x-gen/releases/download/v1.5.0/cxg-linux-amd64"
      sha256 "3c0c28b553c17c95bf2173670ee44b6eee7dfbb0a47c3dc534bb06510c36c7ff"
    end
    on_arm do
      url "https://github.com/Bugb-Technologies/cert-x-gen/releases/download/v1.5.0/cxg-linux-arm64"
      sha256 "845342e4d574c0fcbd747b2c3ce8315d7482bc5a4f99e26bd7144c1b6106997f"
    end
  end

  def install
    bin.install Dir["cxg-*"].first => "cxg"
  end

  # Templates are fetched at first use, not at install time. Running
  # `cxg template update` from post_install writes outside the formula
  # prefix, which Homebrew's install sandbox denies -- it failed the
  # install rather than the download. Tell the user instead.
  def caveats
    <<~EOS
      To download vulnerability detection templates, run:
        cxg template update

      Templates will be installed to ~/.cert-x-gen/templates/
    EOS
  end

  test do
    assert_match "cxg", shell_output("#{bin}/cxg --version")
  end
end
